# Generated by Django 5.2.1 on 2025-05-26 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                related_name="publisher_editors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                related_name="publisher_journalists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
